@startuml
skinparam linetype ortho

interface Entity {
    # position_x: int
    # position_y: int
    + update(): void
    + draw(): void
}

class Pet {
    - Entity: entity
    # hunger: int
    # max_hunger : int
    # exp: int
    # level: int
    # level_cap: int
    # xp_base: int
    # scale: float
    # evolution_one: int
    # evolution_two: int
    # evolution_stage: int
    # happiness: int
    # happiness_cap: int
    # friendship: int
    # hp: int
    # exp_bonus: int
    # hunger_bonus: int
    + update(): void
    + draw(): void
    + feed(food: pet_food_t): void
    + play(): void
    + train(train: pet_train_t): void
    + level_up(): bool
    + evolution(): bool
    + friendship_level(): bool
    + friendship_perks(): void
    + health(): void
    + move(): void
}

class Object {
    - Entity: entity
    - input: string
    + use(): void
}

class Game {
    - pet: Pet
    - input: Input
    # menu_input: int
    + Game(input: Input)
    + start(): void
    + get_user_input(): int
    + menu(): void
    + update(): void
    + render(): void
    + manage_time(): void
}

class Display {
    + show_pet_status(pet: Pet): void
}
class input{
    + update() : void
    + get_select() : bool
    + get_execute() : bool
    + get_cancel() : bool
}

class keyboard {
    - Input: input
    # char select
    # char execute
    # char cancel
    # char ch
    + Keyboard(s: char, e: char, c: char)
    + update(): void
    + get_select(): bool
    + get_execute(): bool
    + get_cancel(): bool
}
class buttons {
    - Input: input
    # char select
    # char execute
    # char cancel
    # char ch
    + update(): void
    + get_select(): bool
    + get_execute(): bool
    + get_cancel(): bool
    button_setup() : void
}

Pet     -up[#DeepPink]-|> Entity
Object  -up[#DeepPink]-|> Entity
Game -[#MediumSlateBlue]-> Pet
Game -[#MediumSlateBlue]-> Object
Game -[#MediumSlateBlue]-> input : uses
keyboard -up[#LimeGreen]-|> input
buttons -up[#LimeGreen]-|> input
@enduml
